service: serverless-lambda-mailer

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
